module.exports = [
  {
    id: 'regione-sicilia-bandi',
    enabled: true,
    parser: 'htmlLinks',
    livello: 'regionale',
    programma: 'Regione Siciliana',
    territorio: 'Sicilia',
    url: 'https://www.regione.sicilia.it/istituzioni/servizi-informativi/bandi',
    selectors: ['main a', 'article a', '.views-row a', '.field-content a'],
    includeKeywords: ['bando', 'avviso', 'agevol', 'finanzi', 'contribut', 'incentiv', 'manifestazione'],
    excludeKeywords: ['privacy', 'cookie', 'accessibil', 'amministrazione trasparente'],
    defaultSettori: ['artigianato', 'commercio', 'turismo'],
    beneficiari: ['PMI', 'Imprese siciliane', 'Enti locali'],
  },
  {
    id: 'invitalia-incentivi',
    enabled: true,
    parser: 'htmlLinks',
    livello: 'nazionale',
    programma: 'Invitalia',
    territorio: 'Italia',
    url: 'https://www.invitalia.it/',
    selectors: ['main a[href*="/incentivi-e-strumenti/"]', '.card a[href*="/incentivi-e-strumenti/"]'],
    includeKeywords: ['impresa', 'incentiv', 'smart', 'sud', 'startup', 'imprese', 'invest', 'bando'],
    excludeKeywords: ['lavora con noi', 'news', 'privacy', 'cookie'],
    defaultSettori: ['startup', 'tecnologia', 'industria'],
    beneficiari: ['PMI', 'Startup', 'Nuove imprese'],
  },
  {
    id: 'ue-funding-opportunities',
    enabled: true,
    parser: 'htmlLinks',
    livello: 'europeo',
    programma: 'UE Funding Opportunities',
    territorio: 'UE e Paesi associati',
    url: 'https://research-and-innovation.ec.europa.eu/funding/funding-opportunities/funding-programmes-and-open-calls_en',
    selectors: ['main a', '.ecl-content-item a', '.listing a'],
    includeKeywords: ['call', 'funding', 'horizon', 'eic', 'digital', 'innovation', 'programme'],
    excludeKeywords: ['cookie', 'contact', 'privacy', 'newsletter'],
    defaultSettori: ['tecnologia', 'startup', 'green'],
    beneficiari: ['PMI', 'Startup', 'Universita', 'Centri di ricerca'],
  },
];
